import { Module } from './types';

export const initialModulesData: Module[] = [
  {
    id: 'gm1',
    name: 'GM 1: Génie Logiciel',
    semester: 1,
    totalCredits: 6,
    subjects: [
      {
        id: 'gm1-1',
        name: 'Génie logiciel (SDLC)',
        coefficient: 3,
        contactHours: 35,
        credit: 3,
        grade: null,
        ds: null,
        projet: null,
        examen: null,
        isSpecialFormula: false,
      },
      {
        id: 'gm1-2',
        name: 'Qualité et Test Logiciels',
        coefficient: 3,
        contactHours: 35,
        credit: 3,
        grade: null,
        ds: null,
        projet: null,
        examen: null,
        isSpecialFormula: false,
      },
    ],
  },
  {
    id: 'gm2',
    name: 'GM 2: Systèmes distribués 1',
    semester: 1,
    totalCredits: 5,
    subjects: [
      {
        id: 'gm2-1',
        name: 'Programmation Concurrente et Parallèle',
        coefficient: 3,
        contactHours: 35,
        credit: 3,
        grade: null,
        ds: null,
        projet: null,
        examen: null,
        isSpecialFormula: false,
      },
      {
        id: 'gm2-2',
        name: 'Développement des systèmes Communicants',
        coefficient: 2,
        contactHours: 28,
        credit: 2,
        grade: null,
        ds: null,
        projet: null,
        examen: null,
        isSpecialFormula: false,
      },
    ],
  },
  {
    id: 'gm3',
    name: 'GM 3: Développement des logiciels1',
    semester: 1,
    totalCredits: 6,
    subjects: [
      {
        id: 'gm3-1',
        name: 'Programmation .NET',
        coefficient: 3,
        contactHours: 35,
        credit: 3,
        grade: null,
        ds: null,
        projet: null,
        examen: null,
        isSpecialFormula: false,
      },
      {
        id: 'gm3-2',
        name: 'Programmation Web avancée',
        coefficient: 3,
        contactHours: 35,
        credit: 3,
        grade: null,
        ds: null,
        projet: null,
        examen: null,
        isSpecialFormula: false,
      },
    ],
  },
  {
    id: 'gm4',
    name: 'GM 4: Infomatique Décisionnelle 1',
    semester: 1,
    totalCredits: 7,
    subjects: [
      {
        id: 'gm4-1',
        name: 'Data Warehouse',
        coefficient: 2,
        contactHours: 35,
        credit: 2,
        grade: null,
        ds: null,
        projet: null,
        examen: null,
        isSpecialFormula: false,
      },
      {
        id: 'gm4-2',
        name: 'Administration des Bases de données',
        coefficient: 2,
        contactHours: 28,
        credit: 2,
        grade: null,
        ds: null,
        projet: null,
        examen: null,
        isSpecialFormula: false,
      },
      {
        id: 'gm4-3',
        name: 'Data Mining',
        coefficient: 3,
        contactHours: 42,
        credit: 3,
        grade: null,
        ds: null,
        projet: null,
        examen: null,
        isSpecialFormula: true,
      },
    ],
  },
  {
    id: 'gm5',
    name: 'GM 5: Préparation à la carrière professionnelle 3',
    semester: 1,
    totalCredits: 4,
    subjects: [
      {
        id: 'gm5-1',
        name: 'Préparation à la certification IELTS 1',
        coefficient: 3,
        contactHours: 35,
        credit: 3,
        grade: null,
        ds: null,
        projet: null,
        examen: null,
        isSpecialFormula: true,
      },
      {
        id: 'gm5-2',
        name: 'Analyse économique des projets innovants',
        coefficient: 1,
        contactHours: 21,
        credit: 1,
        grade: null,
        ds: null,
        projet: null,
        examen: null,
        isSpecialFormula: false,
      },
    ],
  },
  {
    id: 'gm6',
    name: 'GM 6: Génie Logiciel Avancée',
    semester: 2,
    totalCredits: 5,
    subjects: [
      {
        id: 'gm6-1',
        name: 'Modélisation avancée des Systèmes d\'Information',
        coefficient: 2,
        contactHours: 35,
        credit: 2,
        grade: null,
        ds: null,
        projet: null,
        examen: null,
        isSpecialFormula: false,
      },
      {
        id: 'gm6-2',
        name: 'Application dans l\'entreprise: processus et intégration',
        coefficient: 3,
        contactHours: 35,
        credit: 3,
        grade: null,
        ds: null,
        projet: null,
        examen: null,
        isSpecialFormula: false,
      },
    ],
  },
  {
    id: 'gm7',
    name: 'GM 7: Développement des logiciels 2',
    semester: 2,
    totalCredits: 8,
    subjects: [
      {
        id: 'gm7-1',
        name: 'Développement des composants distribués: WEB (JSP,Servlet,JSTL)',
        coefficient: 2,
        contactHours: 28,
        credit: 2,
        grade: null,
        ds: null,
        projet: null,
        examen: null,
        isSpecialFormula: false,
      },
      {
        id: 'gm7-2',
        name: 'Programmation Mobile',
        coefficient: 2,
        contactHours: 35,
        credit: 2,
        grade: null,
        ds: null,
        projet: null,
        examen: null,
        isSpecialFormula: false,
      },
      {
        id: 'gm7-3',
        name: 'Framework web',
        coefficient: 2,
        contactHours: 35,
        credit: 2,
        grade: null,
        ds: null,
        projet: null,
        examen: null,
        isSpecialFormula: false,
      },
      {
        id: 'gm7-4',
        name: 'Interface Homme/Machine',
        coefficient: 2,
        contactHours: 28,
        credit: 2,
        grade: null,
        ds: null,
        projet: null,
        examen: null,
        isSpecialFormula: false,
      },
    ],
  },
  {
    id: 'gm8',
    name: 'GM 8: Systèmes distribués 2',
    semester: 2,
    totalCredits: 5,
    subjects: [
      {
        id: 'gm8-1',
        name: 'Cloud computing',
        coefficient: 3,
        contactHours: 35,
        credit: 3,
        grade: null,
        ds: null,
        projet: null,
        examen: null,
        isSpecialFormula: false,
      },
      {
        id: 'gm8-2',
        name: 'ERP',
        coefficient: 2,
        contactHours: 28,
        credit: 2,
        grade: null,
        ds: null,
        projet: null,
        examen: null,
        isSpecialFormula: false,
      },
    ],
  },
  {
    id: 'gm9',
    name: 'GM 9: Informatique Décisionnelle 2',
    semester: 2,
    totalCredits: 5,
    subjects: [
      {
        id: 'gm9-1',
        name: 'Business Intelligence',
        coefficient: 2,
        contactHours: 28,
        credit: 2,
        grade: null,
        ds: null,
        projet: null,
        examen: null,
        isSpecialFormula: false,
      },
      {
        id: 'gm9-2',
        name: 'Deep Learning',
        coefficient: 3,
        contactHours: 35,
        credit: 3,
        grade: null,
        ds: null,
        projet: null,
        examen: null,
        isSpecialFormula: false,
      },
    ],
  },
  {
    id: 'gm10',
    name: 'GM 10: Préparation à la carrière professionnelle 4',
    semester: 2,
    totalCredits: 5,
    subjects: [
      {
        id: 'gm10-1',
        name: 'Accompagnement startup et création d\'entreprise',
        coefficient: 1,
        contactHours: 21,
        credit: 1,
        grade: null,
        ds: null,
        projet: null,
        examen: null,
        isSpecialFormula: false,
      },
      {
        id: 'gm10-2',
        name: 'Travail en équipe et leadership en ingénierie',
        coefficient: 1,
        contactHours: 21,
        credit: 1,
        grade: null,
        ds: null,
        projet: null,
        examen: null,
        isSpecialFormula: false,
      },
      {
        id: 'gm10-3',
        name: 'Préparation à la certification IELTS 2',
        coefficient: 3,
        contactHours: 35,
        credit: 3,
        grade: null,
        ds: null,
        projet: null,
        examen: null,
        isSpecialFormula: true,
      },
    ],
  },
  {
    id: 'gm11',
    name: 'GM 11: Projet de fin d\'année',
    semester: 2,
    totalCredits: 4,
    subjects: [
      {
        id: 'gm11-1',
        name: 'Projet de fin d\'année',
        coefficient: 4,
        contactHours: 42,
        credit: 4,
        grade: null,
        ds: null,
        projet: null,
        examen: null,
        isSpecialFormula: false,
      },
    ],
  },
];
